services:
  - type: web
    name: travprojekt
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --timeout 60 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: DATA_DIR
        value: /data
    disk:
      name: travdata
      mountPath: /data
      sizeGB: 1
